// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hedixhiyjtxrtgfrognr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZGl4aGl5anR4cnRnZnJvZ25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzE1MDgsImV4cCI6MjA2NDcwNzUwOH0.cu72CgwnJNwoQPcn_m1yFK7UU3pA2F59KezxRvUKNX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);